In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [19]:
# Example random data
data = np.random.rand(5,5)

In [20]:
# Decompose the matrix
U, S, V = np.linalg.svd(data)
S = np.diag(S)

In [21]:
# Full recomposition
r = 5
R = U[:, :r] @ S[:r, :r] @ V[:r, :]

In [22]:
# Comparison
print(np.array_str((R - data), precision=2))

[[-4.37e-16  1.67e-16  5.55e-16  1.67e-16  9.99e-16]
 [-4.51e-16  1.11e-16 -2.50e-16 -1.67e-16  0.00e+00]
 [ 0.00e+00  5.00e-16  4.44e-16 -2.78e-17  0.00e+00]
 [-5.55e-16  3.33e-16 -1.11e-16 -2.22e-16  0.00e+00]
 [ 0.00e+00  3.33e-16  0.00e+00  1.11e-16  3.33e-16]]


In [23]:
# Small recomposition
r = 2
R = U[:, :r] @ S[:r, :r] @ V[:r, :]

array([[0.04379429, 0.42938728, 0.48951055, 0.10304914, 0.64920412],
       [0.04534487, 0.58799569, 0.17643728, 0.36423724, 0.52634966],
       [0.85899311, 0.39986133, 0.66363505, 0.10973282, 0.63312655],
       [0.69788739, 0.73334405, 0.52828034, 0.74089421, 0.4926218 ],
       [0.97193915, 0.61679811, 0.87498795, 0.6668791 , 0.27348961]])